project:
  type: book
  output-dir: docs/

book:
  title: "SignalFlow EEG"
  author: "E. Pedapati"
  date: "6/30/2023"
  search: true
  repo-url: https://github.com/cincibrainlab/SignalFlowEEG
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  sidebar:
    title: " "
    logo: book/sflogo_transparent.png
    style: docked
    background: light
    alignment: center
  comments:
    hypothesis: true
  page-footer:
    left: |
      Guide to Using SignalFlow EEG. ernest.pedapati@cchmc.org
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://cincibrainlab.github.io/SignalFlowEEG/

  chapters:
    - index.qmd

    - part: book/lets-get-started.qmd
      chapters:
        - book/intro.qmd
        - book/references.qmd

    - part: book/vep-tutorial.qmd
      chapters:
        - book/veptutorial/vep1.qmd
        - book/veptutorial/vep2.qmd
      


bibliography: book/references.bib

format:
  html:
    theme: flatly
    number-offset: 1
  pdf:
    documentclass: scrreprt
    number-offset: 1




