---
title: "SignalFlow HBCD Tutorial"
format:
  html:
    code-fold: true
    code-tools: true
    toc: true
    number-sections: true
jupyter: python3
---

Hello Colleagues, today we will be going over the SignalFlow HBCD Tutorial. This tutorial will cover the basics of how to use the SignalFlow HBCD module. This tutorial will cover the following topics:

1. How to setup the SignalFlow HBCD module for script.
2. How to setup the SignalFlow HBCD module for GUI.
3. Changes I made, due to the fact that I do not know the specific requirements of the HBCD module

# How to setup the SignalFlow HBCD module
1. In SignalFlowEEG, go to the zHappeScripts folder. This folder is located in the following directory: /srv/Analysis/Nate_Projects/Github/SignalFlowEEG_HBCD/zHappeScripts. Open this folder as your main Matlab folder. 
2. In the zHappeScripts folder, there is a file called "ExampleHBCDScript.m". This file is the script you can use that has all the modules.
3. Edit the "External dependencies locations" and "Project Information" sections to the correct filepaths. 
4. Left-click the "Run" button in the Matlab toolbar. This will run the script.

# How to start the SignalFlow HBCD module
Our GUI is not able to handle the merging of files. Therefore, we will be using the script to run the first HBCD module.

1. In SignalFlowEEG, go to the zHappeScripts folder. This folder is located in the following directory: /srv/Analysis/Nate_Projects/Github/SignalFlow_Modules_Dev/zHappeScripts. Open this folder as your main Matlab folder. 
2. In the zHappeScripts folder, there is a file called "MergeFasterScript.m". This file is the script you can use that has the first module.
3. Edit the "External dependencies locations" and "Project Information" sections to the correct filepaths. 
4. Left-click the "Run" button in the Matlab toolbar. This will run the script.
5. Navigate to the following directory in Matlab: /srv/Analysis/Nate_Projects/Github/SignalFlowEEG_HBCD 
6. Towards the bottom of the file explorer, there is a file called "SignalFlowEEG_HBCD.mlapp". Right-click this file and left-click "Run". This will open the GUI.
7. In the Setup Tab, follow instructons for the "Setup" section in BasicGUI.qmd.
8. In the Builder Tab, Look at the User Module Library.
9. Add the following modules in order, for information on adding modules to the pipeline see BasicGUI.qmd.
    1. Hbcd
    2. Hbcd Epoching
    3. Export Set
10. Follow the instructions to execute in BasicGUI.qmd.

# Changes I made, due to the fact that I do not know the specific requirements of the HBCD module
I had to make a lot of changes in order to get the HBCD module to work. This was mostly due to the fact that I do not know the specific requirements of the HBCD module. You seem to have a complex folder system that I do not know how to replicate. Please do not run this code as if it was production. If you would liek to use this for production. I would need to have a meeting with you to discuss the specific requirements of the HBCD module.