version: '3.3'
services:
    matlab_dev:
        container_name: matlab_dev
        platform: linux/amd64
        command: ["-vnc"]
        hostname: 001CC2420CA7
        mac_address: 00:1C:C2:42:0C:A7
        user: matlab
        environment:
          - MLM_LICENSE_FILE=/licenses/license.lic
          - HOST=001CC2420CA7
        volumes:
          - './license.lic:/licenses/license.lic'
        ports:
            - 5901:5901
            - 6080:6080
        image:  mathworks/matlab:r2021a
        shm_size: '512M'
        restart: unless-stopped